### PR TITLE
Implementation of some callbacks

### PR DESCRIPTION
**Pull request by matthiascy**
Hi @Twinklebear ,

I added some documentation and implemented following methods.

- [X] device error callback
- [X] device memory monitor callback
- [x] device error code getter
- [X] device property getter
- [X] scene progress monitor callback
- [X] scene flags setter/getter
- [X] scene build quality setter
- [X] geometry subdivision mode setter
- [X] geometry vertex attribute topology setter

Intersection related callbacks are a little bit tricky to implement, still need to some time to do it.

### CODE REVIEW

**Comment by matthiascy** [comment]
It seems like that `rtcInitIntersectContext` doesn't exist in the library on the windows. But why?

**Comment by Twinklebear** [comment]
Awesome thanks @matthiascy !

`rtcInitIntersectContext` should be in the lib, but I see it is missing in https://github.com/Twinklebear/embree-rs/blob/master/src/sys.rs . I think it should be included in the generated bindings, because I whitelist `rtc.*` function names, which should include it.

Let me try regenerating the bindings on the latest Embree release

**Comment by Twinklebear** [comment]
I see now why `rtcInitIntersectContext` isn't there, it's because it's not part of the library, it's inlined: https://github.com/embree/embree/blob/master/include/embree3/rtcore_common.h#L209-L224 . So we need to implement this ourselves in the library to match

**Comment by Twinklebear** [comment]
Cool yeah you're right, I think this looks all good!

**Pull request merged**
